name: beautyplugin
description: 江下科技证件照研究所1
version: 0.0.1
homepage: https://github.com/luokunman/beautyplugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jxtech.beautyplugin.beautyplugin
        pluginClass: BeautypluginPlugin
      ios:
        pluginClass: BeautypluginPlugin
